# Generated by Django 4.0.3 on 2022-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spekar',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
