# Generated by Django 4.0.3 on 2022-03-30 06:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('description', models.CharField(max_length=200, verbose_name='Course Description')),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='')),
                ('lesson', models.IntegerField(default=0)),
                ('durantion', models.DurationField()),
            ],
        ),
    ]
