# Generated by Django 4.0.3 on 2022-03-30 07:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_durantion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=200, verbose_name='Instructor position')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.instructor'),
            preserve_default=False,
        ),
    ]
