# Generated by Django 4.0.3 on 2022-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Price'),
        ),
    ]
