# Generated by Django 4.0.3 on 2022-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Discount Price'),
        ),
    ]
