# Generated by Django 4.0.3 on 2022-03-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.CharField(default=1, max_length=200, verbose_name='Course Discount Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default=1, max_length=200, verbose_name='Course Price'),
            preserve_default=False,
        ),
    ]
