# Generated by Django 4.0.3 on 2022-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_discount_price_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
